import { useEffect, useMemo, useState } from "react";
import {
  Home, IndianRupee, Target, Wallet as WalletIcon, User, MessageCircle, ArrowUpRight, ArrowDownLeft,
  ChevronRight, ShieldCheck, Sparkles, CalendarDays, Landmark, PiggyBank, Bell, Settings2, Plus,
  Pause, Play, CheckCircle2, CircleHelp, BarChart3, Banknote, SlidersHorizontal
} from "lucide-react";
import {
  useAnvesha, recommendedSaving, savingsPlanFor, essentialDaily, flexibleDaily, availableSpending, dailyTotals,
  portalStatuses, emergencyTargetFromExpenses, savedToday, savedOnDate, recommendedSavingForDate, earliestMissingDate, type Tab, type Goal, type SavingsDestination
} from "@/lib/anvesha/store";
import { makeT, inr, LANGUAGES, type Lang } from "@/lib/anvesha/i18n";
import { Button, Card, Field, Choice, Toggle, Progress, AnviBubble, AnviAvatar, Modal, TopBar, Banner, SimNote } from "./ui";
import { GoalForm } from "./Onboarding";
import { cn } from "@/lib/utils";

const NAV: { tab: Tab; icon: typeof Home; key: string }[] = [
  { tab: "home", icon: Home, key: "home" }, { tab: "goals", icon: Target, key: "goals" },
  { tab: "wallet", icon: WalletIcon, key: "wallet" }, { tab: "profile", icon: User, key: "profile" },
];
const today = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };

function BottomNav() {
  const { state, setTab } = useAnvesha(); const t = makeT(state.lang);
  return <nav className="grid grid-cols-4 border-t border-border bg-card px-1 pb-2 pt-1.5">
    {NAV.map(({tab,icon:Icon,key}) => <button key={tab} onClick={()=>setTab(tab)} className={cn("flex flex-col items-center gap-1 py-1.5 text-[10px] font-semibold",state.tab===tab?"text-primary":"text-muted-foreground")}>
      <Icon className="h-5 w-5"/><span>{t(key)}</span>
    </button>)}
  </nav>;
}
function StatCard({label,value,tone="plain",onClick}:{label:string;value:string;tone?:string;onClick?:()=>void}) {
  return <Card onClick={onClick} className={cn(tone==="brand"&&"bg-brand-gradient text-primary-foreground",tone==="warm"&&"bg-accent-soft")}>
    <p className={cn("text-xs",tone==="brand"?"opacity-80":"text-muted-foreground")}>{label}</p><p className="mt-1 text-xl font-bold">{value}</p>
  </Card>;
}
function StatusPill({status}:{status:"complete"|"inProgress"|"needsAttention"|"notStarted"}) {
  const map={complete:["Complete ✓","bg-secondary text-primary"],inProgress:["In progress","bg-accent-soft text-accent"],needsAttention:["Needs attention","bg-accent-soft text-accent"],notStarted:["Not started","bg-muted text-muted-foreground"]} as const;
  return <span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold",map[status][1])}>{map[status][0]}</span>;
}

function HomeTab() {
  const {state,setTab,openOverlay}=useAnvesha(); const t=makeT(state.lang); const rec=recommendedSaving(state); const plan=savingsPlanFor(dailyTotals(state,today()).income||state.todayIncome,dailyTotals(state,today()).expense||state.todayExpenses,state);
  const totals=dailyTotals(state,today()); const income=totals.income||state.todayIncome, expense=totals.expense||state.todayExpenses;
  const statuses=portalStatuses(state);
  const unread=state.notificationsList.filter(n=>!n.read).length;
  useEffect(()=>{
    const hour=new Date().getHours(); const key=`anvesha-checkin-${state.accountId}-${today()}`;
    const hasToday=state.dailyRecords.some(d=>d.date===today()&&d.entries.length>0);
    if(state.loggedIn && state.notifications && hour>=20 && hour<22 && !hasToday && !localStorage.getItem(key)){ openOverlay({kind:"dailyCheckin"}); localStorage.setItem(key,"shown"); }
  },[state.accountId,state.loggedIn,state.notifications,state.dailyRecords.length]);
  const cards=[
    ["Goals",Target,()=>setTab("goals"),"goals" as const],
    ["Emergency Buffer",ShieldCheck,()=>openOverlay({kind:"buffer"}),"emergency" as const],
    ["Budget & Savings",PiggyBank,()=>openOverlay({kind:"budget"}),"budget" as const],
    ["Calendar",CalendarDays,()=>openOverlay({kind:"calendar"}),"complete" as const],
    ["Wallet",WalletIcon,()=>setTab("wallet"),"upi" as const],
    ["Benefits & Schemes",Landmark,()=>openOverlay({kind:"schemes"}),"complete" as const],
    ["Reviews",BarChart3,()=>openOverlay({kind:"reviews"}),"complete" as const],
  ];
  return <div className="space-y-4 px-4 pb-6 pt-1">
    <div className="flex items-center justify-between">
      <div><p className="text-sm text-muted-foreground">{t("goodMorning")}, {state.name} 👋</p><h1 className="text-2xl font-bold">Your money today</h1></div>
      <button onClick={()=>openOverlay({kind:"notifications"})} className="relative rounded-2xl bg-card p-3 shadow-[var(--shadow-card)]"><Bell className="h-5 w-5 text-primary"/>{unread>0&&<span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-accent"/>}</button>
    </div>
    <Card className="bg-brand-gradient text-primary-foreground">
      <div className="flex items-start gap-3"><AnviAvatar size={44}/><div><p className="text-xs font-semibold opacity-80">Anvi</p>
        <p className="mt-1 text-sm leading-relaxed">Today you earned {inr(income)} and spent {inr(expense)}. {rec>0?`You have ${inr(Math.max(0,income-expense))} left after expenses. I suggest ${inr(rec)} as permanent savings${plan.buffer+plan.goal?` plus ${inr(plan.buffer+plan.goal)} for your emergency buffer/goals`:""}, keeping the rest available.`:"Your current saving recommendation is covered for today."}</p>
      </div></div>
      <div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-card/10 p-2"><p className="text-[10px] opacity-75">Earned</p><p className="font-bold">{inr(income)}</p></div><div className="rounded-2xl bg-card/10 p-2"><p className="text-[10px] opacity-75">Spent</p><p className="font-bold">{inr(expense)}</p></div><div className="rounded-2xl bg-card/10 p-2"><p className="text-[10px] opacity-75">Save today</p><p className="font-bold">{inr(plan.total)}</p></div></div>
      {rec>0&&<Button className="mt-3" variant="accent" onClick={()=>openOverlay({kind:"saveAction",amount:rec})}>Save {inr(rec)} today</Button>}
    </Card>
    <div className="grid grid-cols-2 gap-3"><StatCard label="Already saved" value={inr(state.savedThisWeek)} tone="warm"/><StatCard label="Available money" value={inr(availableSpending(state))}/></div>
    <div className="grid grid-cols-2 gap-3"><StatCard label="Emergency buffer" value={`${inr(state.emergencyBuffer)} / ${inr(state.emergencyBufferTarget)}`} onClick={()=>openOverlay({kind:"buffer"})}/><StatCard label="Savings wallet" value={inr(state.walletBalance)} tone="brand" onClick={()=>setTab("wallet")}/></div>
    <div><div className="mb-2 flex items-center justify-between"><h2 className="font-bold">Your portals</h2><button onClick={()=>openOverlay({kind:"help"})} className="text-xs font-semibold text-primary">Ask Anvi</button></div>
      <div className="grid grid-cols-2 gap-2.5">{cards.map(([label,Icon,action,status])=> <div key={label as string} className="relative rounded-2xl border border-border bg-card p-3 text-left shadow-[var(--shadow-card)]">
        <button onClick={action as ()=>void} className="w-full text-left active:scale-[.99]">
          <div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="h-4 w-4"/></span><StatusPill status={statuses[status as keyof typeof statuses]??"complete"}/></div>
          <div className="mt-2 flex items-center justify-between gap-2"><p className="text-sm font-semibold">{label as string}</p><div className="animate-anvi-float"><AnviAvatar size={28}/></div></div><p className="mt-1 text-[10px] text-muted-foreground">Anvi can explain this</p><ChevronRight className="mt-1 h-4 w-4 text-muted-foreground"/>
        </button>
        <button aria-label={`Explain ${label}`} onClick={()=>openOverlay({kind:"portalInfo",portal:String(label)})} className="absolute right-2 top-2 rounded-full bg-secondary p-1.5 text-primary"><CircleHelp className="h-3.5 w-3.5"/></button>
      </div>)}</div>
    </div>
    <Button variant="outline" onClick={()=>openOverlay({kind:"extraMoney"})}><Plus className="h-4 w-4"/> I have extra money</Button>
  </div>;
}

function MoneyTab() {
  const {state,addDailyRecord,openOverlay}=useAnvesha(); const [type,setType]=useState<"income"|"expense">("income"); const [amount,setAmount]=useState(""); const [category,setCategory]=useState("Fuel"); const [note,setNote]=useState(""); const [error,setError]=useState("");
  const date=today(), totals=dailyTotals(state,date), rec=recommendedSaving(state);
  const add=()=>{const v=Number(amount); if(!v||v<=0)return setError("Please enter a valid amount."); addDailyRecord(date,type==="income"?v:0,type==="expense"?v:0,type==="expense"?category:"Income",note);setAmount("");setNote("");setError("");};
  return <div className="space-y-4 px-4 pb-6 pt-1"><TopBar title="Daily Money"/><AnviBubble>Record income or expenses whenever they happen. You can add as many entries as you need.</AnviBubble>
    <div className="grid grid-cols-2 gap-2"><Choice columns={2} value={type} onChange={v=>setType(v as any)} options={[{value:"income",label:"Add income"},{value:"expense",label:"Add expense"}]}/></div>
    <Card><Field label={type==="income"?"Income amount (₹)":"Expense amount (₹)"} inputMode="numeric" value={amount} onChange={e=>{setAmount(e.target.value.replace(/\D/g,""));setError("")}} placeholder="0"/>
      {type==="expense"&&<div className="mt-3"><p className="mb-1.5 text-sm font-medium">Category</p><Choice columns={2} value={category} onChange={setCategory} options={["Fuel","Food","Vehicle","Family","Education","Medical","Other"].map(x=>({value:x,label:x}))}/></div>}
      <div className="mt-3"><Field label="Note (optional)" value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. lunch"/></div>
      {error&&<Banner tone="error">{error}</Banner>}<Button className="mt-3" onClick={add}><Plus className="h-4 w-4"/> Add {type}</Button>
    </Card>
    <div className="grid grid-cols-2 gap-3"><StatCard label="Total income" value={inr(totals.income||state.todayIncome)}/><StatCard label="Total expenses" value={inr(totals.expense||state.todayExpenses)}/></div>
    <Card><div className="flex items-center justify-between"><p className="font-semibold">Today's entries</p><button className="text-xs font-semibold text-primary" onClick={()=>openOverlay({kind:"calendar"})}>Open calendar</button></div>
      <div className="mt-2 divide-y divide-border">{(state.dailyRecords.find(d=>d.date===date)?.entries??[]).slice().reverse().map(e=><div key={e.id} className="flex items-center justify-between py-2.5"><div><p className="text-sm font-medium">{e.category??"Entry"}</p><p className="text-xs text-muted-foreground">{e.note||"Today"}</p></div><p className={cn("font-semibold",e.income>0?"text-primary":"text-foreground")}>{e.income>0?"+":"-"}{inr(e.income||e.expense)}</p></div>)}</div>
    </Card>
    <Card className="bg-accent-soft"><p className="font-semibold">Today's adaptive saving</p><p className="mt-1 text-sm">After today's recorded expenses, you have <b>{inr(Math.max(0, totals.income - totals.expense))}</b> left. I suggest saving <b>{inr(rec)}</b> and keeping the rest available for you.</p>{rec>0&&<Button className="mt-3" variant="accent" onClick={()=>openOverlay({kind:"saveAction",amount:rec})}>Save {inr(rec)} today</Button>}{rec===0&&totals.income>totals.expense&&<p className="mt-2 text-xs text-muted-foreground">You have money left, but today's recommended saving is already covered or is currently zero.</p>}</Card>
  </div>;
}

function CalendarTab() {
  const {state,addDailyRecord,editDailyEntry,deleteDailyEntry,closeOverlay}=useAnvesha(); const [month,setMonth]=useState(new Date()); const [selected,setSelected]=useState(today()); const [type,setType]=useState<"income"|"expense">("income"); const [amount,setAmount]=useState(""); const [category,setCategory]=useState("Fuel"); const [editing,setEditing]=useState<string|null>(null); const [editAmount,setEditAmount]=useState("");
  const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(); const selectedTotals=dailyTotals(state,selected);
  const rec=recommendedSavingForDate(state,selected); const nextAllowed=earliestMissingDate(state,today()); const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1);
  return <div className="space-y-4"><AnviBubble>I’m your money diary here. Choose a date to record income, expenses, your daily budget, savings and where money was set aside.</AnviBubble><div className="flex items-center justify-between"><button onClick={()=>setMonth(new Date(y,m-1,1))} className="rounded-xl bg-secondary px-3 py-2">‹</button><p className="font-bold">{month.toLocaleString("en-IN",{month:"long",year:"numeric"})}</p><button onClick={()=>setMonth(new Date(y,m+1,1))} className="rounded-xl bg-secondary px-3 py-2">›</button></div>
    <div className="grid grid-cols-7 gap-1 text-center text-xs"><div className="col-span-7 grid grid-cols-7 pb-1 text-muted-foreground">{["S","M","T","W","T","F","S"].map((x,i)=><span key={i}>{x}</span>)}</div>
      {cells.map((d,i)=>{if(!d)return <span key={i}/>;const ds=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`, r=dailyTotals(state,ds), stateDot=r.income&&r.expense?"bg-primary":r.income||r.expense?"bg-accent":"bg-muted";const locked=ds>nextAllowed; return <button key={ds} disabled={locked} onClick={()=>setSelected(ds)} className={cn("relative rounded-xl p-2",selected===ds&&"bg-secondary ring-2 ring-primary/20",locked&&"opacity-35 cursor-not-allowed")}><span>{d}</span><span className={cn("mx-auto mt-1 block h-1.5 w-1.5 rounded-full",stateDot)}/></button>})}</div>
    <Card className="bg-secondary"><p className="font-semibold">{new Date(selected+"T12:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long"})}</p><div className="mt-3 grid grid-cols-2 gap-2"><Row label="Total income" value={inr(selectedTotals.income)}/><Row label="Total expenses" value={inr(selectedTotals.expense)}/><Row label="Already saved" value={inr(savedOnDate(state,selected))}/><Row label="Recommended saving" value={inr(rec)}/></div></Card>
    <Card><p className="font-semibold">Complete day report</p><p className="mt-1 text-xs text-muted-foreground">Income, expenses, budget, savings, diversions and recorded activity for this day.</p><div className="mt-2 divide-y divide-border">{(state.dailyRecords.find(d=>d.date===selected)?.entries??[]).map(e=>editing===e.id?<div key={e.id} className="py-2.5"><div className="flex gap-2"><Field label="Amount" inputMode="numeric" value={editAmount} onChange={ev=>setEditAmount(ev.target.value.replace(/\D/g,""))}/><Button full={false} onClick={()=>{const v=Number(editAmount);if(v>0) editDailyEntry(selected,e.id,e.income?{income:v,expense:0}:{income:0,expense:v});setEditing(null)}}>Save</Button></div></div>:<div key={e.id} className="flex items-center justify-between gap-2 py-2.5"><div><p className="text-sm font-medium">{e.category||"Entry"}</p><p className="text-xs text-muted-foreground">{e.note||""}</p></div><div className="flex items-center gap-2"><span className="font-semibold">{e.income?`+${inr(e.income)}`:`-${inr(e.expense)}`}</span><button className="text-xs font-semibold text-primary" onClick={()=>{setEditing(e.id);setEditAmount(String(e.income||e.expense))}}>Edit</button><button className="text-xs font-semibold text-destructive" onClick={()=>deleteDailyEntry(selected,e.id)}>Delete</button></div></div>)}</div>
      <div className="mt-3 grid grid-cols-2 gap-2"><Choice columns={2} value={type} onChange={v=>setType(v as any)} options={[{value:"income",label:"Income"},{value:"expense",label:"Expense"}]}/><Field label="Amount" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))}/></div>
      {type==="expense"&&<div className="mt-2"><Choice columns={2} value={category} onChange={setCategory} options={["Fuel","Food","Vehicle","Family","Medical","Other"].map(x=>({value:x,label:x}))}/></div>}
      <Button className="mt-3" onClick={()=>{const v=Number(amount);if(v>0){addDailyRecord(selected,type==="income"?v:0,type==="expense"?v:0,category);setAmount("")}}}>Add to {selected}</Button>
    </Card><Card><p className="font-semibold">Activity on this day</p><div className="mt-2 space-y-2">{state.activityLog.filter(a=>a.date===selected).slice().reverse().map(a=><div key={a.id} className="rounded-xl bg-secondary px-3 py-2"><p className="text-xs font-semibold">{a.time}</p><p className="text-xs text-muted-foreground">{a.action}</p></div>)}{state.activityLog.filter(a=>a.date===selected).length===0&&<p className="text-xs text-muted-foreground">No recorded app activity for this day.</p>}</div></Card><Button variant="ghost" onClick={closeOverlay}>Close calendar</Button>
  </div>;
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between rounded-xl bg-card px-3 py-2"><span className="text-xs text-muted-foreground">{label}</span><span className="text-sm font-semibold">{value}</span></div>}

function GoalsTab(){
  const {state,openOverlay,set}=useAnvesha(); return <div className="space-y-4 px-4 pb-6 pt-1"><TopBar title="Goals"/>
    <AnviBubble>Choose a goal and I’ll help you decide how fast to reach it. Pausing a goal never deletes the money already associated with it.</AnviBubble>
    {state.goals.map(g=><Card key={g.id} onClick={()=>openOverlay({kind:"goalDetail",id:g.id})}><div className="flex items-start justify-between"><div><p className="font-semibold">{g.name}</p><p className="mt-1 text-xs text-muted-foreground">{inr(g.current)} of {inr(g.target)} · by {g.targetDate}</p></div><span className="text-xs font-semibold text-accent">{Math.round(g.current/g.target*100)}%</span></div><div className="mt-3"><Progress value={g.current} max={g.target}/></div><div className="mt-2 flex items-center justify-between"><span className="text-xs text-muted-foreground">{g.status==="paused"?"Paused":g.status==="completed"?"Completed":"Active"}</span><ChevronRight className="h-4 w-4 text-muted-foreground"/></div></Card>)}
    <Button variant="accent" onClick={()=>openOverlay({kind:"addGoal"})}><Plus className="h-4 w-4"/> Add another goal</Button>
  </div>;
}

function WalletTab(){
 const {state,openOverlay}=useAnvesha(); const goalSavings=state.goals.reduce((s,g)=>s+g.current,0); return <div className="space-y-4 px-4 pb-6 pt-1"><TopBar title="Wallet"/>
 <Card className="bg-brand-gradient text-primary-foreground"><p className="text-xs opacity-80">Simulated savings wallet</p><p className="mt-1 text-3xl font-bold">{inr(state.walletBalance)}</p><p className="mt-1 text-xs opacity-80">No real money moves in this prototype.</p></Card>
 <div className="grid grid-cols-2 gap-3"><StatCard label="Emergency buffer" value={inr(state.emergencyBuffer)} onClick={()=>openOverlay({kind:"buffer"})}/><StatCard label="Goal-wise savings" value={inr(goalSavings)}/><StatCard label="General savings" value={inr(state.generalSavings)}/><StatCard label="UPI status" value={state.upiConnected?"Connected":"Not connected"}/></div>
 <div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>openOverlay({kind:"withdraw"})}><ArrowDownLeft className="h-4 w-4"/> Withdraw</Button><Button variant="accent" onClick={()=>openOverlay({kind:"extraMoney"})}><ArrowUpRight className="h-4 w-4"/> Add savings</Button></div>
 <Card><p className="font-semibold">Recent transactions</p>{state.transactions.slice(0,8).map(t=><div key={t.id} className="flex items-center justify-between border-b border-border py-2.5 last:border-0"><div><p className="text-sm">{t.label}</p><p className="text-xs text-muted-foreground">{t.when}</p></div><span className={cn("font-semibold",t.type==="deposit"?"text-primary":"text-foreground")}>{t.type==="deposit"?"+":"-"}{inr(t.amount)}</span></div>)}</Card>
 <SimNote text="Prototype simulation — no real money is transferred. Never enter a UPI PIN or bank password."/>
 </div>;
}

function ProfileTab(){
 const {state,set,openOverlay,go}=useAnvesha(); return <div className="space-y-4 px-4 pb-6 pt-1"><TopBar title="Profile"/>
 <Card className="flex items-center gap-3"><AnviAvatar size={52}/><div><p className="font-bold">{state.name}</p><p className="text-xs text-muted-foreground">{state.occupation} · {state.city}</p><p className="mt-1 text-xs text-primary">{state.lang.toUpperCase()}</p></div></Card>
 <div className="space-y-2"><Card onClick={()=>go("personal")}><div className="flex items-center justify-between"><span className="font-semibold">Personal information</span><ChevronRight className="h-4 w-4"/></div></Card><Card onClick={()=>go("financial")}><div className="flex items-center justify-between"><span className="font-semibold">Financial information</span><ChevronRight className="h-4 w-4"/></div></Card><Card onClick={()=>openOverlay({kind:"settings"})}><div className="flex items-center justify-between"><span className="font-semibold">Settings & privacy</span><Settings2 className="h-4 w-4"/></div></Card><Card onClick={()=>openOverlay({kind:"reviews"})}><div className="flex items-center justify-between"><span className="font-semibold">Reviews</span><BarChart3 className="h-4 w-4"/></div></Card><Card onClick={()=>openOverlay({kind:"help"})}><div className="flex items-center justify-between"><span className="font-semibold">Help & Anvi</span><CircleHelp className="h-4 w-4"/></div></Card></div>
 <Button variant="ghost" onClick={()=>{set({loggedIn:false});go("auth")}}>Log out</Button>
 </div>;
}

function SaveActionSheet({amount}:{amount:number}){
 const {state,applySavingsPlan,closeOverlay,setTab}=useAnvesha(); const [custom,setCustom]=useState(String(Math.max(0,amount))); const [phase,setPhase]=useState<"confirm"|"loading"|"done">("confirm"); const v=Number(custom); const basePlan=savingsPlanFor(dailyTotals(state,today()).income||state.todayIncome,dailyTotals(state,today()).expense||state.todayExpenses,state); const adjustedPlan={...basePlan,permanent:Math.min(v,Math.max(0,basePlan.permanent)),total:Math.min(v,Math.max(0,basePlan.permanent))+basePlan.buffer+basePlan.goal};
 if(!state.upiConnected)return <Modal open onClose={closeOverlay} title="UPI not connected"><Banner tone="error">Connect UPI before using this simulated savings action.</Banner><Button className="mt-3" onClick={()=>{closeOverlay();}}>Close</Button></Modal>;
 return <Modal open onClose={closeOverlay} title={phase==="done"?"Saving confirmed":"Confirm today's saving"} dismissible={phase!=="loading"}>{phase==="done"?<div className="space-y-3"><Banner tone="success">{inr(v)} permanent savings confirmed{adjustedPlan.buffer+adjustedPlan.goal?` + ${inr(adjustedPlan.buffer+adjustedPlan.goal)} set aside for buffer/goals`:""}.</Banner><Card className="bg-secondary"><Row label="Recommended" value={inr(amount)}/><Row label="Already saved this week" value={inr(state.savedThisWeek)}/><Row label="Wallet balance" value={inr(state.walletBalance)}/></Card><SimNote text="Prototype simulation — no real money transferred."/><Button onClick={()=>{closeOverlay();setTab("wallet")}}>View wallet</Button></div>:<div className="space-y-3"><AnviBubble>Every saving action needs your confirmation. I never auto-save.</AnviBubble><Field label="How much would you like to save? (₹)" inputMode="numeric" value={custom} onChange={e=>setCustom(e.target.value.replace(/\D/g,""))}/><Choice columns={2} value={custom===String(amount)?"recommended":custom} onChange={x=>{if(x==="recommended")setCustom(String(amount));if(x==="smaller")setCustom(String(Math.max(0,Math.floor(amount/2))))}} options={[{value:"recommended",label:`Recommended ${inr(amount)}`},{value:"smaller",label:`Smaller ${inr(Math.floor(amount/2))}`} ]}/><Button loading={phase==="loading"} disabled={!v || v > Math.max(0, amount)} onClick={()=>{setPhase("loading");setTimeout(()=>{applySavingsPlan({...adjustedPlan,total:adjustedPlan.permanent+adjustedPlan.buffer+adjustedPlan.goal});setPhase("done")},700)}}>Confirm save {inr(v||0)}</Button><Button variant="ghost" onClick={closeOverlay}>Not today</Button><SimNote text="No automatic saving. Your money stays under your control." /></div>}</Modal>;
}

function WithdrawSheet(){const {state,withdraw,closeOverlay}=useAnvesha();const [amount,setAmount]=useState("");const [phase,setPhase]=useState<"form"|"loading"|"done">("form");const v=Number(amount);return <Modal open onClose={closeOverlay} title="Withdraw savings" dismissible={phase!=="loading"}>{phase==="done"?<div className="space-y-3"><Banner tone="success">{inr(v)} withdrawal simulated successfully.</Banner><Row label="New wallet balance" value={inr(state.walletBalance)}/><SimNote text="No real money moved."/><Button onClick={closeOverlay}>Done</Button></div>:<div className="space-y-3"><Field label="Amount (₹)" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))}/><p className="text-xs text-muted-foreground">Available: {inr(state.walletBalance)} · UPI: {state.upiConnected?state.upiId:"not connected"}</p><Button disabled={!state.upiConnected||!v||v>state.walletBalance} loading={phase==="loading"} onClick={()=>{setPhase("loading");setTimeout(()=>{withdraw(v);setPhase("done")},700)}}>Confirm withdrawal</Button><SimNote text="Prototype simulation — no real money is transferred." /></div>}</Modal>}

function GoalDetailSheet({id}:{id:string}){const {state,set,deposit,closeOverlay}=useAnvesha();const g=state.goals.find(x=>x.id===id);const [amount,setAmount]=useState("100");const [target,setTarget]=useState(String(g?.target??0));if(!g)return null;const pct=Math.min(100,Math.round(g.current/g.target*100));return <Modal open onClose={closeOverlay} title={g.name}><div className="space-y-3"><Card className="bg-accent-soft"><p className="text-2xl font-bold text-accent">{inr(g.current)} <span className="text-sm text-muted-foreground">/ {inr(g.target)}</span></p><Progress value={g.current} max={g.target}/><p className="mt-2 text-xs text-muted-foreground">{pct}% complete · {inr(Math.max(0,g.target-g.current))} remaining · deadline {g.targetDate}</p></Card><AnviBubble>{pct>70?"You're close!":"Small regular contributions can make this easier."}</AnviBubble><Field label="Add to this goal (₹)" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))}/><Button variant="accent" disabled={!state.upiConnected||!Number(amount)||g.status!=="active"} onClick={()=>deposit(Number(amount),g.id)}>Save to goal</Button><Card><p className="text-sm font-semibold">Change target</p><div className="mt-2 flex gap-2"><Field label="Target (₹)" inputMode="numeric" value={target} onChange={e=>setTarget(e.target.value.replace(/\D/g,""))}/><Button full={false} onClick={()=>{const v=Number(target);if(v>0)set({goals:state.goals.map(x=>x.id===g.id?{...x,target:v,status:x.current>=v?"completed":x.status}:x)})}}>Save</Button></div></Card><div className="grid grid-cols-2 gap-2"><Button variant="outline" disabled={g.status==="completed"} onClick={()=>set({goals:state.goals.map(x=>x.id===g.id?{...x,status:x.status==="paused"?"active":"paused"}:x)})}>{g.status==="paused"?<><Play className="h-4 w-4"/> Resume</>:<><Pause className="h-4 w-4"/> Pause</>}</Button><Button variant="outline" onClick={()=>{const d=prompt("New deadline (YYYY-MM-DD)",g.targetDate);if(d)set({goals:state.goals.map(x=>x.id===g.id?{...x,targetDate:d}:x)})}}>Change deadline</Button></div><SimNote text="Saved money remains associated with this goal when paused." /></div></Modal>}
function AddGoalSheet(){const {state,set,closeOverlay}=useAnvesha();return <Modal open onClose={closeOverlay} title="Create a goal"><GoalForm saveLabel="Create goal" onCancel={closeOverlay} onSave={g=>{set({goals:[...state.goals,g]});closeOverlay()}}/></Modal>}

function BufferSheet(){const {state,set,closeOverlay}=useAnvesha();const target=state.emergencyBufferTarget||emergencyTargetFromExpenses(state);const [v,setV]=useState(String(target));return <Modal open onClose={closeOverlay} title="Emergency Buffer"><AnviBubble>Your buffer is separate from goal savings. It is a cushion for medical emergencies, vehicle repairs and income gaps.</AnviBubble><Card className="mt-3 bg-secondary"><Row label="Current buffer" value={inr(state.emergencyBuffer)}/><Row label="Recommended target" value={inr(target)}/><Progress value={state.emergencyBuffer} max={target}/></Card><Field className="mt-3" label="Change target (₹)" inputMode="numeric" value={v} onChange={e=>setV(e.target.value.replace(/\D/g,""))}/><Button onClick={()=>{set({emergencyBufferTarget:Number(v)||target});closeOverlay()}}>Save target</Button><SimNote text="Anvesha never transfers money without your confirmation." /></Modal>}

function BudgetSheet(){const {state,closeOverlay}=useAnvesha();const rec=recommendedSaving(state);const income=dailyTotals(state,today()).income||state.todayIncome,expense=dailyTotals(state,today()).expense||state.todayExpenses;return <Modal open onClose={closeOverlay} title="Budget & adaptive savings"><AnviBubble>This plan changes with your actual income, expenses, commitments, existing savings and emergency needs. There is no mandatory percentage.</AnviBubble><div className="mt-3 space-y-2"><Row label="Income" value={inr(income)}/><Row label="Essential expenses" value={inr(essentialDaily(state))}/><Row label="Flexible expenses" value={inr(flexibleDaily(state))}/><Row label="Today's recorded expenses" value={inr(expense)}/><Row label="Recommended saving" value={inr(rec)}/><Row label="Already saved today" value={inr(savedToday(state))}/><Row label="Available money" value={inr(availableSpending(state))}/></div><Card className="mt-3 bg-accent-soft"><p className="font-semibold">Example</p><p className="mt-1 text-sm">₹1,050 income − ₹400 expenses can leave around ₹100 as a recommendation; the rest stays available to you.</p></Card><Button className="mt-3" onClick={closeOverlay}>Got it</Button></Modal>}

function ExtraMoneySheet(){const {state,allocateSavings,closeOverlay}=useAnvesha();const [amount,setAmount]=useState("");const [destination,setDestination]=useState("buffer");const v=Number(amount);const options=[{value:"buffer",label:"Emergency Buffer"},{value:"goal",label:"Goal"},{value:"general",label:"General Savings"},{value:"long",label:"Long-Term Saving"},{value:"debt",label:"Debt repayment"}];return <Modal open onClose={closeOverlay} title="I have extra money"><AnviBubble>I’ll suggest a destination based on your current situation, but you decide where it goes.</AnviBubble><Field className="mt-3" label="Extra amount (₹)" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))}/><div className="mt-3"><Choice value={destination} onChange={setDestination} options={options}/></div><Card className="mt-3 bg-accent-soft"><p className="text-sm font-semibold">Anvesha's suggestion</p><p className="mt-1 text-xs">Because your emergency buffer is {Math.round(state.emergencyBuffer/state.emergencyBufferTarget*100)}% funded, prioritising it is a reasonable prototype suggestion.</p></Card><Button className="mt-3" disabled={!v} onClick={()=>{const goal=state.goals.find(g=>g.status==="active");allocateSavings(v,destination as SavingsDestination,destination==="goal"?goal?.id:undefined);closeOverlay()}}>Confirm destination</Button><SimNote text="This is a prototype allocation. No real money is moved." /></Modal>}

function NotificationsSheet(){const {state,markNotificationRead,closeOverlay}=useAnvesha();return <Modal open onClose={closeOverlay} title="Notifications"><div className="space-y-2">{state.notificationsList.map(n=><button key={n.id} onClick={()=>markNotificationRead(n.id)} className={cn("w-full rounded-2xl border p-3 text-left",n.read?"bg-card":"bg-secondary")}><div className="flex items-start gap-2"><Bell className="mt-0.5 h-4 w-4 text-primary"/><div><p className="text-sm font-semibold">{n.title}</p><p className="mt-1 text-xs text-muted-foreground">{n.body}</p></div></div></button>)}</div></Modal>}

function ReviewsSheet(){const {state,closeOverlay,go}=useAnvesha();const now=new Date();const mp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;const yp=String(now.getFullYear());const calc=(prefix:string)=>state.dailyRecords.filter(d=>d.date.startsWith(prefix)).reduce((a,d)=>{const t=dailyTotals(state,d.date);return {income:a.income+t.income,expense:a.expense+t.expense}},{income:0,expense:0});const m=calc(mp),y=calc(yp);return <Modal open onClose={closeOverlay} title="Reviews"><div className="space-y-3"><AnviBubble>Here’s a simple review, without financial jargon. Reviews help you notice patterns, not judge yourself.</AnviBubble><Card><p className="font-semibold">Monthly review</p><div className="mt-2 grid grid-cols-2 gap-2"><Row label="Total income" value={inr(m.income)}/><Row label="Total expenses" value={inr(m.expense)}/><Row label="Total saved" value={inr(state.savedThisWeek)}/><Row label="Goal progress" value={`${state.goals.filter(g=>g.status==="completed").length} complete`}/><Row label="Buffer progress" value={`${state.emergencyBufferTarget?Math.min(100,Math.round(state.emergencyBuffer/state.emergencyBufferTarget*100)):0}%`}/></div></Card><Card><p className="font-semibold">Yearly review</p><div className="mt-2 grid grid-cols-2 gap-2"><Row label="Yearly income" value={inr(y.income)}/><Row label="Yearly expenses" value={inr(y.expense)}/><Row label="Savings balance" value={inr(state.walletBalance)}/><Row label="Goals completed" value={String(state.goals.filter(g=>g.status==="completed").length)}/></div></Card><Card className="bg-accent-soft"><p className="font-semibold">Anvi's insight</p><p className="mt-1 text-sm">{m.income>m.expense?"Your recorded income is ahead of expenses this month. Keep saving flexible.":"Expenses are taking more of your recorded income this month. Protect essentials first; saving can wait on difficult days."}</p></Card><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>{closeOverlay();go("personal")}}>Review personal data</Button><Button variant="outline" onClick={()=>{closeOverlay();go("financial")}}>Review financial data</Button></div><Button onClick={closeOverlay}>Done</Button></div></Modal>}

function SchemesSheet(){const {closeOverlay}=useAnvesha();return <Modal open onClose={closeOverlay} title="Benefits & Schemes"><AnviBubble>I’ll keep this simple. These are suggestions to explore, not guaranteed eligibility and not products sold by Anvesha.</AnviBubble><div className="mt-3 space-y-2">{[["Government schemes","Check official government sources for schemes relevant to your state and work profile."],["Recurring deposit","A small recurring deposit can build a habit if your cash flow allows it."],["Fixed deposit","For genuinely extra money, compare FD rates and terms before choosing."]].map(([a,b])=><Card key={a}><p className="font-semibold">{a}</p><p className="mt-1 text-xs text-muted-foreground">{b}</p></Card>)}</div><SimNote text="Prototype examples only. No application or purchase happens here."/><Button className="mt-3" onClick={closeOverlay}>Done</Button></Modal>}

const HELP_QA=[["What is Emergency Buffer?","It is a separate cushion for medical needs, vehicle repairs and income gaps."],["What does Wallet do?","Wallet shows your simulated savings, goal allocations and transactions. No real money moves."],["How do I record money?","Use Calendar to record multiple income and expense entries for each day."],["Why did my saving change?","The recommendation adapts to actual income, expenses and your emergency needs."],["How do I withdraw?","Open Wallet, choose Withdraw and confirm. It is only a prototype simulation."],["What happens if I press this?","Tell me the feature name and I’ll explain what it does and where it goes."]];
function HelpSheet(){const {state,closeOverlay}=useAnvesha();const [input,setInput]=useState("");const [thread,setThread]=useState([{from:"anvi",text:`Hi ${state.name}! I'm Anvi. Ask me anything about your money.`}]);const answer=(q:string)=>{const f=HELP_QA.find(([a])=>a.toLowerCase()===q.toLowerCase());if(f)return f[1];const l=q.toLowerCase();if(l.includes("save"))return `Today I suggest about ${inr(recommendedSaving(state))} if your recorded income and expenses support it.`;if(l.includes("goal"))return state.goals.length?`Your active goal is ${state.goals[0].name}, at ${inr(state.goals[0].current)} of ${inr(state.goals[0].target)}.`:"You haven't created a goal yet.";return "I can explain Calendar, Wallet, Goals, Emergency Buffer, Budget, notifications and adaptive savings.";};const ask=(q:string)=>{if(!q.trim())return;setThread(t=>[...t,{from:"you",text:q}]);setInput("");setTimeout(()=>setThread(t=>[...t,{from:"anvi",text:answer(q)}]),250)};return <Modal open onClose={closeOverlay} title="Ask Anvi"><div className="mb-2 flex flex-wrap gap-2">{HELP_QA.map(([q])=><button key={q} onClick={()=>ask(q)} className="rounded-full bg-secondary px-3 py-2 text-xs font-medium">{q}</button>)}</div><div className="max-h-64 space-y-2 overflow-y-auto rounded-2xl bg-muted p-3">{thread.map((m,i)=><div key={i} className={m.from==="anvi"?"flex gap-2":"text-right"}>{m.from==="anvi"&&<AnviAvatar size={26}/>}<span className={cn("inline-block max-w-[82%] rounded-2xl px-3 py-2 text-xs",m.from==="anvi"?"bg-card":"bg-primary text-primary-foreground")}>{m.text}</span></div>)}</div><div className="mt-3 flex gap-2"><input className="flex-1 rounded-2xl border border-border px-3 py-2 text-sm" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask(input)} placeholder="Ask Anvi…"/><Button full={false} onClick={()=>ask(input)}>Send</Button></div></Modal>}

function SettingsSheet(){const {state,set,closeOverlay,go,openOverlay}=useAnvesha();return <Modal open onClose={closeOverlay} title="Settings & Privacy"><div className="space-y-3"><Card><p className="font-semibold">Privacy</p><p className="mt-1 text-xs text-muted-foreground">We only ask for information needed to help manage savings. We never ask for a UPI PIN or banking password.</p></Card><Toggle label="Location permission" checked={state.locationPermission==="granted"} onChange={v=>set({locationPermission:v?"granted":"denied"})}/><Toggle label="Notifications" checked={state.notifications} onChange={v=>set({notifications:v})}/><Toggle label="Anonymous usage data" checked={state.analyticsConsent} onChange={v=>set({analyticsConsent:v})}/><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>{closeOverlay();go("personal");}}>Personal Information</Button><Button variant="outline" onClick={()=>{closeOverlay();go("financial");}}>Financial Information</Button></div><Button variant="outline" onClick={()=>{closeOverlay();openOverlay({kind:"budget"});}}>View / Edit Budget</Button><div><p className="mb-2 text-sm font-semibold">Language</p><Choice columns={2} value={state.lang} onChange={v=>set({lang:v as Lang})} options={LANGUAGES.map(l=>({value:l.code,label:`${l.native} (${l.english})`}))}/></div><Card><p className="text-sm font-semibold">UPI connection</p><p className="mt-1 text-xs text-muted-foreground">{state.upiConnected?state.upiId:"Not connected"}</p><Button className="mt-2" variant="outline" disabled={!state.upiConnected} onClick={()=>set({upiConnected:false})}>Disconnect UPI</Button></Card><Button onClick={closeOverlay}>Save & close</Button></div></Modal>}

export function MainApp(){
 const {state,openOverlay}=useAnvesha();
 return <div className="flex h-full flex-col bg-background"><main className="min-h-0 flex-1 overflow-y-auto no-scrollbar">{state.tab==="home"&&<HomeTab/>}{state.tab==="money"&&<MoneyTab/>}{state.tab==="goals"&&<GoalsTab/>}{state.tab==="wallet"&&<WalletTab/>}{state.tab==="profile"&&<ProfileTab/>}</main><button onClick={()=>openOverlay({kind:"help"})} className="absolute bottom-[74px] right-5 flex h-12 w-12 items-center justify-center rounded-full bg-brand-gradient text-primary-foreground shadow-[var(--shadow-float)]"><AnviAvatar size={40}/></button><BottomNav/>
 {state.tab==="home"&&null}
 <Overlays/>
 </div>;
}
function PortalInfoSheet({portal}:{portal:string}){ const {state,closeOverlay}=useAnvesha(); const map:Record<string,string>={Goals:"Create and manage savings goals.","Emergency Buffer":"Build a separate emergency cushion.","Budget & Savings":"See a flexible spending and savings recommendation.",Calendar:"Review complete historical day reports.",Wallet:"See simulated savings and transactions.","Benefits & Schemes":"Explore clearly labelled prototype scheme information.",Reviews:"Review your month and year with Anvi."}; return <Modal open onClose={closeOverlay} title={portal}><div className="space-y-3"><div className="flex items-start gap-3"><AnviAvatar size={50}/><AnviBubble>{map[portal]||`This portal helps you manage ${portal.toLowerCase()}. You can open it whenever you need it.`}</AnviBubble></div><Button onClick={closeOverlay}>Got it</Button></div></Modal> }
function DailyCheckinSheet(){const {closeOverlay,openOverlay}=useAnvesha(); return <Modal open onClose={closeOverlay} title="Anvi's daily check-in"><div className="space-y-3"><div className="flex items-start gap-3"><AnviAvatar size={54}/><AnviBubble>Hi! I haven’t seen today’s money record yet. Want to quickly add what you earned and spent in your Calendar?</AnviBubble></div><Button onClick={()=>{closeOverlay();openOverlay({kind:"calendar"})}}>Open calendar</Button><Button variant="ghost" onClick={closeOverlay}>Not now</Button></div></Modal>}

function Overlays(){const {state}=useAnvesha();return <>{state.screen==="app"&&state.tab&&null}{/* overlay rendering lives above the tab content */}<OverlayRouter/></>}
function OverlayRouter(){const {overlay,closeOverlay}=useAnvesha();switch(overlay.kind){case"calendar":return <Modal open onClose={closeOverlay} title="Money calendar"><CalendarTab/></Modal>;case"saveAction":return <SaveActionSheet amount={overlay.amount}/>;case"withdraw":return <WithdrawSheet/>;case"help":return <HelpSheet/>;case"goalDetail":return <GoalDetailSheet id={overlay.id}/>;case"addGoal":return <AddGoalSheet/>;case"notifications":return <NotificationsSheet/>;case"reviews":return <ReviewsSheet/>;case"schemes":return <SchemesSheet/>;case"extraMoney":return <ExtraMoneySheet/>;case"buffer":return <BufferSheet/>;case"budget":return <BudgetSheet/>;case"settings":return <SettingsSheet/>;case"portalInfo":return <PortalInfoSheet portal={overlay.portal}/>;case"dailyCheckin":return <DailyCheckinSheet/>;default:return null}}
